./AlphaTree config/config_trie_8bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_10bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_12bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_14bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_16bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_18bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_21bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_24bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_28bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_32bit_4N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_64bit_4N.txt | tee -a output/out_trie.txt

./AlphaTree config/config_trie_8bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_10bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_12bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_14bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_16bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_18bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_21bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_24bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_28bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_32bit_8N.txt | tee -a output/out_trie.txt
./AlphaTree config/config_trie_64bit_8N.txt | tee -a output/out_trie.txt