./AlphaTree config/config_hhpq_8bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_10bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_12bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_14bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_16bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_18bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_21bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_24bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_28bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_32bit_4N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_64bit_4N.txt | tee -a output/out_hhpq.txt

./AlphaTree config/config_hhpq_8bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_10bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_12bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_14bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_16bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_18bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_21bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_24bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_28bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_32bit_8N.txt | tee -a output/out_hhpq.txt
./AlphaTree config/config_hhpq_64bit_8N.txt | tee -a output/out_hhpq.txt