./AlphaTree config/config_uf_8bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_10bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_12bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_14bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_16bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_18bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_21bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_24bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_28bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_32bit_4N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_64bit_4N.txt | tee -a output/out_uf.txt

./AlphaTree config/config_uf_8bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_10bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_12bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_14bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_16bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_18bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_21bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_24bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_28bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_32bit_8N.txt | tee -a output/out_uf.txt
./AlphaTree config/config_uf_64bit_8N.txt | tee -a output/out_uf.txt