./AlphaTree config/config_heap_8bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_10bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_12bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_14bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_16bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_18bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_21bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_24bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_28bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_32bit_4N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_64bit_4N.txt | tee -a output/out_heap.txt

./AlphaTree config/config_heap_8bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_10bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_12bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_14bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_16bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_18bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_21bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_24bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_28bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_32bit_8N.txt | tee -a output/out_heap.txt
./AlphaTree config/config_heap_64bit_8N.txt | tee -a output/out_heap.txt